// const sampleListings = [
//   {
//     title: "Cozy Beachfront Cottage",
//     description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
//     image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60",
//     price: 1500,
//     location: "Malibu",
//     country: "United States",
//   },
//   {
//     title: "Modern Loft in Downtown",
//     description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
//     image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
//     price: 1200,
//     location: "New York City",
//     country: "United States",
//   },
//   {
//     title: "Mountain Retreat",
//     description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
//     image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60",
//     price: 1000,
//     location: "Aspen",
//     country: "United States",
//   },
//   {
//     title: "Historic Villa in Tuscany",
//     description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
//     image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
//     price: 2500,
//     location: "Florence",
//     country: "Italy",
//   },
//   {
//     title: "Secluded Treehouse Getaway",
//     description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
//     image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60",
//     price: 800,
//     location: "Portland",
//     country: "United States",
//   },
//   {
//     title: "Beachfront Paradise",
//     description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
//     image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=60",
//     price: 2000,
//     location: "Cancun",
//     country: "Mexico",
//   },
//   {
//     title: "Rustic Cabin by the Lake",
//     description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
//     image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
//     price: 900,
//     location: "Lake Tahoe",
//     country: "United States",
//   },
//   {
//     title: "Luxury Penthouse with City Views",
//     description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
//     image: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?auto=format&fit=crop&w=800&q=60",
//     price: 3500,
//     location: "Los Angeles",
//     country: "United States",
//   },
//   {
//     title: "Ski-In/Ski-Out Chalet",
//     description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
//     image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=60",
//     price: 3000,
//     location: "Verbier",
//     country: "Switzerland",
//   },
//   {
//     title: "Safari Lodge in the Serengeti",
//     description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
//     image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=60",
//     price: 4000,
//     location: "Serengeti National Park",
//     country: "Tanzania",
//   },
//   {
//     title: "Historic Canal House",
//     description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
//     image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60",
//     price: 1800,
//     location: "Amsterdam",
//     country: "Netherlands",
//   },
//   {
//     title: "Private Island Retreat",
//     description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
//     image: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?auto=format&fit=crop&w=800&q=60",
//     price: 10000,
//     location: "Fiji",
//     country: "Fiji",
//   },
//   {
//     title: "Charming Cottage in the Cotswolds",
//     description: "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
//     image: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?auto=format&fit=crop&w=800&q=60",
//     price: 1200,
//     location: "Cotswolds",
//     country: "United Kingdom",
//   },
//   {
//     title: "Historic Brownstone in Boston",
//     description: "Step back in time in this elegant historic brownstone located in the heart of Boston.",
//     image: "https://images.unsplash.com/photo-1533619239233-6280475a633a?auto=format&fit=crop&w=800&q=60",
//     price: 2200,
//     location: "Boston",
//     country: "United States",
//   },
//   {
//     title: "Beachfront Bungalow in Bali",
//     description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
//     image: "https://images.unsplash.com/photo-1602391833977-358a52198938?auto=format&fit=crop&w=800&q=60",
//     price: 1800,
//     location: "Bali",
//     country: "Indonesia",
//   },
//   {
//     title: "Mountain View Cabin in Banff",
//     description: "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
//     image: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?auto=format&fit=crop&w=800&q=60",
//     price: 1500,
//     location: "Banff",
//     country: "Canada",
//   },
//   {
//     title: "Art Deco Apartment in Miami",
//     description: "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
//     image: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?auto=format&fit=crop&w=800&q=60",
//     price: 1600,
//     location: "Miami",
//     country: "United States",
//   },
//   {
//     title: "Tropical Villa in Phuket",
//     description: "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
//     image: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?auto=format&fit=crop&w=800&q=60",
//     price: 3000,
//     location: "Phuket",
//     country: "Thailand",
//   },
//   {
//     title: "Historic Castle in Scotland",
//     description: "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
//     image: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=800&q=60",
//     price: 4000,
//     location: "Scottish Highlands",
//     country: "United Kingdom",
//   },
//   {
//     title: "Desert Oasis in Dubai",
//     description: "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
//     image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60",
//     price: 5000,
//     location: "Dubai",
//     country: "United Arab Emirates",
//   }
// ];

// module.exports = { data: sampleListings };














const sampleListings = [
  {
    title: "Beachside Villa in Goa",
    description: "Wake up to the sound of waves in this beautiful beachside villa. Perfect for a relaxing vacation near Goa's famous beaches.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Goa",
    country: "India",
  },
 {
  title: "Heritage Haveli in Jaipur",
  description: "Experience royal Rajasthani hospitality in this beautifully restored heritage haveli near historic forts and palaces.",
  image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=60",
  price: 2800,
  location: "Jaipur",
  country: "India",
},
  {
    title: "Houseboat Stay in Alleppey",
    description: "Cruise through Kerala's serene backwaters while enjoying a luxurious houseboat experience.",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=800&q=60",
    price: 4200,
    location: "Alleppey",
    country: "India",
  },
  {
    title: "Mountain Cabin in Manali",
    description: "Surrounded by snow-capped peaks and pine forests, this cozy cabin is perfect for nature lovers.",
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Manali",
    country: "India",
  },
  {
    title: "Lake View Retreat in Udaipur",
    description: "Enjoy breathtaking views of Lake Pichola from this elegant retreat in the City of Lakes.",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=800&q=60",
    price: 3800,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Tea Estate Cottage in Munnar",
    description: "Stay amidst lush tea plantations and rolling hills in this peaceful cottage.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Munnar",
    country: "India",
  },
  {
    title: "Luxury Tent in Jaisalmer",
    description: "Experience the magic of the Thar Desert with cultural performances and a luxury desert camp stay.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Riverside Cottage in Rishikesh",
    description: "Relax by the Ganges and enjoy yoga, adventure sports, and peaceful surroundings.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    price: 2000,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Hilltop Homestay in Darjeeling",
    description: "Wake up to stunning Himalayan views and explore Darjeeling's famous tea gardens.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
    price: 2400,
    location: "Darjeeling",
    country: "India",
  },
  {
    title: "Beach Resort in Pondicherry",
    description: "Enjoy French-inspired charm and pristine beaches in this stylish seaside resort.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
    price: 3200,
    location: "Pondicherry",
    country: "India",
  },
  {
    title: "Snow View Chalet in Gulmarg",
    description: "Perfect for skiing enthusiasts and mountain lovers, offering spectacular snowy landscapes.",
    image: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=60",
    price: 4500,
    location: "Gulmarg",
    country: "India",
  },
  {
    title: "Coffee Estate Stay in Coorg",
    description: "Escape into nature with a stay surrounded by coffee plantations and misty hills.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    price: 2700,
    location: "Coorg",
    country: "India",
  },
  {
    title: "Island Retreat in Andaman",
    description: "Experience crystal-clear waters, white-sand beaches, and unforgettable sunsets.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 5500,
    location: "Havelock Island",
    country: "India",
  },
  {
    title: "Valley View Cottage in Shillong",
    description: "Discover the beauty of Northeast India from this cozy cottage overlooking lush valleys.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=60",
    price: 2300,
    location: "Shillong",
    country: "India",
  },
  {
    title: "Luxury House in Hyderabad",
    description: "Stay in a modern luxury home with easy access to Charminar, Golconda Fort, and the city's food scene.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Hyderabad",
    country: "India",
  },
  {
    title: "Lakefront Villa in Nainital",
    description: "Enjoy serene lake views and cool mountain weather from this beautiful villa.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    price: 2900,
    location: "Nainital",
    country: "India",
  },
  {
    title: "Beach Cottage in Gokarna",
    description: "A peaceful coastal getaway with pristine beaches and laid-back vibes.",
    image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=800&q=60",
    price: 2600,
    location: "Gokarna",
    country: "India",
  },
  {
    title: "Eco Resort in Kaziranga",
    description: "Explore wildlife and enjoy a unique stay close to the famous national park.",
    image: "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=800&q=60",
    price: 3100,
    location: "Kaziranga",
    country: "India",
  },
  {
    title: "Royal Palace Stay in Mysore",
    description: "Experience the grandeur of Mysore with a luxurious stay inspired by royal architecture.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
    price: 4000,
    location: "Mysore",
    country: "India",
  },
];

module.exports = { data: sampleListings };